project:
  type: website
  output-dir: docs

website:
  search: false
#  location: navbar
#  title: "STATA FR"
  page-navigation: true
  page-footer: 
    left: "Marc Thévenin / Ined-Sms / Juillet 2023"
    background: dark
  navbar:
    left: 
      - href: index.qmd
        text: "Stata Ined"
      - href: articles/index.qmd
        text: "Articles"
      - text: Formations
        menu: 
          - text: "Formation initiale"
            href: https://mthevenin.github.io/stata_programmation/
          - text: "Graphiques"
            href: https://mthevenin.github.io/stata_graphiques/           
  sidebar:
    align: center
    tools: 
      - href: about.qmd
      - icon: github
        href: https://github.com/mthevenin
      - icon: envelope
        href: mailto:marc.thevenin@ined.fr 
      - icon: file-person
        href: about.qmd
    style: docked
    search: true
    contents:
      - href: maj.qmd
      - href: versions.qmd
      - href: conferences.qmd
      - href: Stata_journal.qmd      

format:
  html:
    theme: [yeti, styles.scss] 
    css: styles.css
    code-background: true
    code-copy: true
highlight-style: dracula
#    toc: true
#    toc-depth: 3
#    toc-title: Sections
#number-sections: true


execute: 
  freeze: auto



