project:
  type: website
  output-dir: docs

website:
  search: 
    location: navbar
  page-navigation: true
  page-footer: 
    left: "Marc Thévenin / Ined-Sms / Mai 2023"
    background: dark
  navbar:
    left:
      - href: index.qmd
        text: "Stata Ined"
      - href: https://mthevenin.github.io/stata_graphiques/
        text: "Graphiques"     
      - text: "Programmation"
        href: https://mthevenin.github.io/stata_programmation/    

  sidebar:
    pinned: true
    align: center
    tools: 
      - href: about.qmd
      - icon: github
        href: https://github.com/mthevenin
      - icon: envelope
        href: mailto:marc.thevenin@ined.fr 
      - icon: file-person
        href: about.qmd

    style: docked
    search: true
    contents:
      - href: maj.qmd
      - href: versions.qmd
      - href: conferences.qmd
      - href: Stata_journal.qmd      

format:
  html:
    theme: [yeti, theme-light.scss] 
    css: styles.css
    code-background: true
    code-copy: true
    toc: true
    toc-depth: 3
    toc-title: Sections
number-sections: true




