---
title: "Conférences"

format:
  html:
    toc: true
---

Liste non exhaustive des conférences depuis 2019. J'ai sélectionné les conférences dont les présentations sont disponibles et principalement en anglais.


:::  {.callout-note appearance="simple" icon="false"}
## **2023**

-   **US**: <https://www.stata.com/meeting/us23/>
    - Présentations disponibles
-   **CAN**: <https://www.stata.com/meeting/canada23/>
    - Présentations disponibles
-   **FR**: <https://www.stata.com/meeting/france23/>
    - Présentations disponibles
-   **Virtual symposium (biostatistique et épidémiologie)**: <https://www.stata.com/symposiums/biostatistics-and-epidemiology23/>
    - Présentations disponibles
-   **AUS**: <https://www.stata.com/meeting/oceania23/>
    - Présentations et/ou vidéos disponibles

:::


:::  {.callout-note appearance="simple" icon="false"}
## **2022**

Beaucoup de conférences prévues à l'automne, en particulier celle qui se déroulera en angleterre.

-   **Virtual symposium**: <https://www.stata.com/symposiums/economics22/>
    -   Certaines présentations disponibles
-   **CH**: <https://www.stata.com/meeting/switzerland22/>
    - présentations disponibles.
-   **UK**: <https://www.stata.com/meeting/uk22/>
    -   Présentations disponibles.
-   **US**: <https://www.stata.com/meeting/us22/>
    -   Présentations disponibles
-   **FR**: <https://www.stata.com/meeting/france22/>
    -   Econométrie appliquée, pas d'éléments propres à la programmation ou aux mises à jour du logiciel
    -   Certaines présentations sont disponibles
-   **IT**: <https://www.stata.com/meeting/italy22/>
:::


:::  {.callout-note appearance="simple" icon="false"}
## **2021**

-   **USA**: <https://www.stata.com/meeting/us21/>

-   **UK**: <https://www.stata.com/meeting/uk21/>

-   **CAN**: <https://www.stata.com/meeting/canada21/>
:::

:::  {.callout-note appearance="simple" icon="false"}
## **2020**

-   **USA**: <https://www.stata.com/meeting/us20/>

    -   Voir: ***The causal effects of parents' marital status on children's earnings***

-   **UK**: <https://www.stata.com/meeting/uk20/>

-   **CH**: <https://www.stata.com/meeting/switzerland20/>

-   **POR**: <https://www.stata.com/meeting/portugal20/>
:::

:::  {.callout-note appearance="simple" icon="false"}
## **2019**

-   **USA**: <https://www.stata.com/meeting/chicago19/>

-   **UK**: <https://www.stata.com/meeting/uk19/>

-   **AUS**: <https://www.stata.com/meeting/oceania19/>
:::
