---
title: "Versions Stata"
---


```{r setup, include=FALSE}
## Global options
knitr::opts_chunk$set(cache = TRUE)

library(knitr)
library (shiny)
library (rsconnect)
library(haven)
library(pander)
library(memisc)
library(fontawesome)
```

<br><br>

# **Version 18 (mai 2023)**

Je viens juste d'avoir la mise à jour de la version 18. On peut trouver la liste des mise à jour [ici](https://www.stata.com/new-in-stata/)

Quelques remarques sur ce que j'ai rapidement regardé/testé:

- Présence d'une autosave pour l'éditeur de programme...enfin [(lien article)](https://mthevenin.github.io/stata_fr/articles/index/posts/autosave/autosave.html)
- Graphiques: 
  - Nouvelle palette de couleur et nouveau thème par défaut... enfin [(lien article)](https://mthevenin.github.io/stata_graphiques/formation/formation23.html)
  - Nouvelle(s) option(s) qui modifient la syntaxe d'empilement d'objets graphiques (`colorvar`). Déjà quelques réserves si l'empilement est relatif à une troisième variable de type discrète (on empilait avec des `if`). La syntaxe des options semblent un peu lourde pour pas grand chose [(article site officiel)](https://www.stata.com/new-in-stata/graph-colors-by-variable/). Cela me semble plus intéressant si la troisième variable est de type continue, même si la paramétrisation de me semble pas top. A remarqué qu'avec `colorvar()` on ne peut plus directement chargé une palette de couleur avec `grstyle set color` de B.Jann. On doit passer par `colorpalette` et inserer dans une option la macro `r(p)`.  
- Les frames:
  - nouvelle extension avec .dtas qui enregistrent directement une suite de frame liées (pas testé mais cela me semble très intéressant).
  - possibilité de supprimer plusieurs frame actives avec `frame drop` (non testé).


# **Versions installées (2022)**

**Versions à l'Ined**  

Sauf exception les versions windows et linux sont en version 17 SE. La version 16 avait été partiellement déployée sous windows en 2020, alors que la version précédente linux était la 15 (2017).  
A noter pour la version linux, utilisée principalement pour le personnel non titutaire, qu'il est possible depuis la version 16 d'importer directement des bases en format *Sas* avec la commande **`import sas`**. Pour les exportations de fichiers .dta en .sas7bdat, il est toujours recommandé d'utiliser la commande **`savasas`** (`findit saswrapper`)   


**Ajouts et améliorations avec la version 17**:  <https://www.stata.com/new-in-stata/> 

- **Amélioration du temps d'exécution**: sans comparation avec les versions antérieures, on note une nette amélioration du temps d'exécution en particulier pour la commande `collapse`, la commande `sort` et les opérations qui lui sont associées, par exemple avec le prefixe `bysort` (voir la note de version en lien ci-dessus). Associées aux commande du package **`gtools`** le gain de temps apparait encore plus considérable pour des opérations sur des bases de données volumineuses. Les fonctionnalités de ce package seront décrites dans la partie dédiée à la programmation (lien à venir).

- **Wishlist**: Vous pouvez alimenter la whishlist de la version 18 (printemps 2023) .... cela fait de nombreuses années qu'une autosave de l'éditeur de programme est demandé. Cela va bien finir par arriver un jour: <https://www.statalist.org/forums/forum/general-stata-discussion/general>.


# Mise à jour de la version

Au cours des deux années d'existence d'une version, plusieurs mises à jour visant à fixer des bugs sont disponibles. Si on saute une ou plusieurs maj, la dernière met à jour l'ensemble (cela sera forcément un peu plus long)

* Consultation des mises à jours (avec contenu): **`update query`**

* Installation de la mise à jour
  - Le fichier ouvert avec `update query` propose d'installer la ou les mises à jour. Toutes les sessions devront être fermée avant l'installation.
  - A l'Ined, la mise à jour ne peut se faire que sous son **compte administrateur**. Ce type de session a été mise en place il y a quelques années par le service informatique. Si vous ne l'avez jamais utilisé ou oublié, il faut entrer son login administrateur et un mot de passe.  *Normalement*:
    - Login: **adm_nom**. Pour moi donc: *adm_thevenin*
    - Mot De Passe: le mot de passe du *sceau ined* (sous condition, j'ai du mettre un mdp différent à mon retour de détachement). 
    - Si problème: contacter le service informatique à l'adresse <support-micro@ined.fr>  
    
    
    







