---
title: "**Stata, Jupyter et Quarto: solution ultime avec nbstata**"

title-block-banner: false

author: 
  - name: "Marc Thévenin"
    affiliations:
      - name: "Ined"

date: 07/26/2023

categories:
  - Notebook
  - Quarto
  - Jupyter

format: 
  html: default
#  docx:
#    toc: true
#    number-sections: true
    
filters:
   - lightbox
lightbox: auto

#jupyter: nbstata  

abstract: | 
 putdoc, puthtml... Oublier! Depuis plusieurs années il est possible d'exécuter un programme Stata avec le notebook Jupyter avec le `Stata_kernel` de K.Barron ou plus récemment avec la librairie officielle `pystata` (version 17). Du côté de RStudio on pouvait également exécuter un programme Stata dans un document Rmarkdown, avec la librairie `statamarkdown`.  En 2022 avec l'arrivée de **Quarto**, évolution de  rmarkdown, et le nouveau noyau Jupyter **`nbstata`** de **Tim Huegerich**, on dispose d'une solution particulièrement efficace pour produire toute sorte de documentation (site, article, ouvrage).
 
---

* Documentation nbstata: <https://github.com/hugetim/nbstata>

* Prérequis: Stata 17 minimum


Avant de débuter ce tutoriel, concernant les avantages et les inconvénients d'utiliser le notebook Jupyter:   

* Les graphiques sont afficher sous le programme et non dans une fenêtre externe.  

* Le programme est exécuter dans des cellules de code et non dans un éditeur de programme. Avec Jupyter, les macros temporaires (`local`) restent enregistrer d'une cellule de code à une autre. 

* le noyau `nbstata` permet d'enregistrer l'ensemble des cellules dans un fichier .do.

* Niveau inconvénient ou limite d'utilisation. Les notebooks ne permettent pas d'afficher à la volée la base de données ou la frame active. Son utilisation n'est donc pas forcément adaptée au traitement et à la manipulation d'une base de données.


# Installation de Jupyter

Une fiche dans la base d'assistance [**assistoolsms**](https://mthevenin.github.io/assistoolsms/) est déjà disponible
[[Lien](https://mthevenin.github.io/assistoolsms/R/assist/posts/R_jupyter/R_jupyter.html#installation)]. A l'Ined l'installation est largement facilité avec l'outil **applined** mise à disposition par le service informatique.


# Installation de nbstata


# Utilisation de nbstata dans un notebook Jupyter


# Utilisation de nbstata dans un document Quarto














